-- NEXOTFE - Migration historica neutralizada (nao executa DDL)
--
-- Esta migration era um arquivo de consolidacao para execucao manual
-- no SQL Editor do Supabase Dashboard (nao fazia parte da cadeia
-- sequencial de migrations aplicada pela CLI). Seu conteudo original
-- (tabelas, indices, colunas, trigger, policies, funcoes e views de
-- itens_industriais/boms/bom_itens/ordens_fabricacao) e integralmente
-- produzido pelas migrations 202606050032, 202606050033, 202606050034
-- e 202606050035 -- nenhum objeto era exclusivo desta migration.
--
-- Investigacao read-only (rodada de regularizacao fundacional do
-- NEXOTFE) confirmou, por comparacao objeto a objeto com as migrations
-- de origem e com o catalogo do dump certificado de 21/06/2026
-- (nexotfe_public_20260621_000436.dump), que nenhuma definicao
-- divergia -- os dois CREATE TRIGGER e as quatro CREATE POLICY
-- duplicados eram o unico motivo de falha em um fresh replay
-- sequencial (CREATE TRIGGER e CREATE POLICY nao aceitam IF NOT
-- EXISTS neste PostgreSQL).
--
-- Esta version (202606050036) permanece no historico apenas para
-- preservar o tracking; o conteudo executavel foi removido para que
-- um fresh replay sequencial (schema vazio ate a ultima migration)
-- reproduza o estado certificado sem tentar recriar objetos ja
-- existentes. Nenhuma alteracao de estado, semantica ou objeto foi
-- feita -- apenas remocao de SQL redundante ja comprovado equivalente.
